/**
 * Web Bluetooth communication with Phomemo M110 thermal printer.
 * Based on the proven Phomymo open-source implementation.
 * 
 * Label size: 70x50mm at 203 DPI = 559x399 pixels
 * Printer width: 384 pixels (48 bytes)
 */

// Phomemo BLE Service UUIDs (from Phomymo project)
const SERVICE_UUIDS = [
  0xff00,
  0xffe0,
  0xae30,
  '49535343-fe7d-4ae5-8fa9-9fafd205e455',
  '0000ff00-0000-1000-8000-00805f9b34fb',
] as const;

// Write characteristic UUIDs
const WRITE_CHAR_UUIDS = [
  0xff02,
  'bef8d6c9-9c21-4c9e-b632-bd58c1009f9f',
  '49535343-8841-43f4-a8d4-ecbe34729bb3',
];

// Printer constants
const BLE_CHUNK_SIZE = 128;
const BLE_CHUNK_DELAY_MS = 20;

export interface PrinterConnection {
  device: any;
  characteristic: any;
  writeMethod: 'withoutResponse' | 'withResponse';
}

/** Check if Web Bluetooth is supported */
export function isBluetoothSupported(): boolean {
  return typeof navigator !== 'undefined' && 'bluetooth' in (navigator as any);
}

/** Connect to a Phomemo M110 printer via Web Bluetooth */
export async function connectPrinter(): Promise<PrinterConnection> {
  if (!isBluetoothSupported()) {
    throw new Error('Web Bluetooth stöds inte i denna webbläsare. Använd Chrome eller Edge.');
  }

  let device: any;
  try {
    device = await (navigator as any).bluetooth.requestDevice({
      filters: [
        { namePrefix: 'M' }, { namePrefix: 'D' }, { namePrefix: 'P' },
        { namePrefix: 'Q' }, { namePrefix: 'T' }, { namePrefix: 'A' },
        { namePrefix: 'Mr.in' }, { namePrefix: 'Phomemo' },
      ],
      optionalServices: SERVICE_UUIDS as any,
    });
  } catch {
    // Fallback: show all BLE devices
    device = await (navigator as any).bluetooth.requestDevice({
      acceptAllDevices: true,
      optionalServices: SERVICE_UUIDS as any,
    });
  }

  const server = await connectWithRetry(device);

  // Find service
  let service: any = null;
  for (const uuid of SERVICE_UUIDS) {
    try {
      service = await server.getPrimaryService(uuid as any);
      break;
    } catch { /* try next */ }
  }
  if (!service) throw new Error('Kunde inte hitta skrivarens BLE-tjänst. Kontrollera att skrivaren är påslagen.');

  // Find write characteristic
  let characteristic: any = null;
  for (const uuid of WRITE_CHAR_UUIDS) {
    try {
      characteristic = await service.getCharacteristic(uuid as any);
      break;
    } catch { /* try next */ }
  }
  if (!characteristic) throw new Error('Kunde inte hitta skrivarens BLE-karaktäristik.');

  // Detect write method
  const writeMethod = characteristic.properties.writeWithoutResponse ? 'withoutResponse' : 'withResponse';

  return { device, characteristic, writeMethod };
}

/** Connect to GATT server with retry */
async function connectWithRetry(device: any, retries = 1): Promise<any> {
  for (let attempt = 0; attempt <= retries; attempt++) {
    try {
      const server = await device.gatt!.connect();
      return server;
    } catch (e) {
      if (attempt < retries) {
        await delay(300 * (attempt + 1));
      } else {
        throw new Error('Kunde inte ansluta till skrivaren. Försök stänga av och slå på den.');
      }
    }
  }
  throw new Error('Anslutning misslyckades.');
}

/** Disconnect from printer */
export function disconnectPrinter(connection: PrinterConnection): void {
  try {
    connection.device.gatt?.disconnect();
  } catch { /* ignore */ }
}

/** Send raw bytes in chunks */
async function sendChunked(conn: PrinterConnection, data: Uint8Array): Promise<void> {
  for (let offset = 0; offset < data.length; offset += BLE_CHUNK_SIZE) {
    const chunk = data.slice(offset, offset + BLE_CHUNK_SIZE);
    if (conn.writeMethod === 'withoutResponse') {
      await conn.characteristic.writeValueWithoutResponse(chunk);
    } else {
      await conn.characteristic.writeValueWithResponse(chunk);
    }
    if (offset + BLE_CHUNK_SIZE < data.length) {
      await delay(BLE_CHUNK_DELAY_MS);
    }
  }
}

function delay(ms: number): Promise<void> {
  return new Promise(r => setTimeout(r, ms));
}

export interface PrintProgress {
  phase: string;
  percent: number;
}

/**
 * Print canvas to Phomemo M110 using M110-specific ESC/POS commands.
 * Canvas should already be 384px wide (generated by LabelCanvas).
 * onProgress is called with phase updates for UI feedback.
 */
export async function printBitmap(
  connection: PrinterConnection,
  canvas: HTMLCanvasElement,
  copies: number = 1,
  density: number = 8,
  onProgress?: (p: PrintProgress) => void,
): Promise<void> {
  onProgress?.({ phase: 'Förbereder bild...', percent: 5 });

  const width = canvas.width;
  const height = canvas.height;
  const ctx = canvas.getContext('2d')!;
  const imageData = ctx.getImageData(0, 0, width, height);

  // Dither to 1-bit
  onProgress?.({ phase: 'Dithar bild...', percent: 10 });
  const pixels = ditherToMonochrome(imageData);

  const bytesPerRow = Math.ceil(width / 8);
  const bitmapData = new Uint8Array(bytesPerRow * height);
  for (let y = 0; y < height; y++) {
    for (let x = 0; x < width; x++) {
      if (pixels[y * width + x] === 0) {
        const byteIdx = y * bytesPerRow + Math.floor(x / 8);
        const bitIdx = 7 - (x % 8);
        bitmapData[byteIdx] |= (1 << bitIdx);
      }
    }
  }

  const clampedDensity = Math.max(1, Math.min(15, density));

  for (let copy = 0; copy < copies; copy++) {
    const copyLabel = copies > 1 ? ` (${copy + 1}/${copies})` : '';
    const basePercent = 15 + (copy / copies) * 80;

    // 1. Initialize printer
    onProgress?.({ phase: `Initierar skrivare${copyLabel}...`, percent: basePercent });
    await sendChunked(connection, new Uint8Array([0x1B, 0x40]));
    await delay(50);

    // 2. Set speed
    await sendChunked(connection, new Uint8Array([0x1B, 0x4E, 0x0D, 5]));
    await delay(20);

    // 3. Set density
    await sendChunked(connection, new Uint8Array([0x1B, 0x4E, 0x04, clampedDensity]));
    await delay(20);

    // 4. Set media type (label with gap)
    await sendChunked(connection, new Uint8Array([0x1F, 0x11, 0x0A]));
    await delay(20);

    // 5. Send raster header + bitmap
    onProgress?.({ phase: `Skickar bilddata${copyLabel}...`, percent: basePercent + 10 });
    const header = new Uint8Array([
      0x1D, 0x76, 0x30, 0x00,
      bytesPerRow & 0xFF, (bytesPerRow >> 8) & 0xFF,
      height & 0xFF, (height >> 8) & 0xFF,
    ]);

    const fullData = new Uint8Array(header.length + bitmapData.length);
    fullData.set(header, 0);
    fullData.set(bitmapData, header.length);

    // Send in chunks with progress updates
    const totalChunks = Math.ceil(fullData.length / BLE_CHUNK_SIZE);
    for (let i = 0; i < totalChunks; i++) {
      const chunk = fullData.slice(i * BLE_CHUNK_SIZE, (i + 1) * BLE_CHUNK_SIZE);
      if (connection.writeMethod === 'withoutResponse') {
        await connection.characteristic.writeValueWithoutResponse(chunk);
      } else {
        await connection.characteristic.writeValueWithResponse(chunk);
      }
      if (i < totalChunks - 1) await delay(BLE_CHUNK_DELAY_MS);

      // Update progress every 10 chunks
      if (i % 10 === 0) {
        const chunkPercent = basePercent + 10 + (i / totalChunks) * 60 * (1 / copies);
        onProgress?.({ phase: `Skickar bilddata${copyLabel}...`, percent: Math.min(95, chunkPercent) });
      }
    }

    // 6. Footer sequence
    await delay(100);
    await sendChunked(connection, new Uint8Array([0x1F, 0xF0, 0x05, 0x00]));
    await delay(50);
    await sendChunked(connection, new Uint8Array([0x1F, 0xF0, 0x03, 0x00]));
    await delay(300);

    if (copy < copies - 1) await delay(500);
  }

  onProgress?.({ phase: 'Klar!', percent: 100 });
}

/**
 * Floyd-Steinberg dithering: converts RGBA image data to array of 0 (black) or 255 (white).
 */
function ditherToMonochrome(imageData: ImageData): Uint8Array {
  const w = imageData.width;
  const h = imageData.height;
  const data = imageData.data;

  const gray = new Float32Array(w * h);
  for (let i = 0; i < w * h; i++) {
    const r = data[i * 4];
    const g = data[i * 4 + 1];
    const b = data[i * 4 + 2];
    const a = data[i * 4 + 3];
    const alpha = a / 255;
    gray[i] = (0.299 * r + 0.587 * g + 0.114 * b) * alpha + 255 * (1 - alpha);
  }

  const result = new Uint8Array(w * h);
  for (let y = 0; y < h; y++) {
    for (let x = 0; x < w; x++) {
      const idx = y * w + x;
      const oldVal = gray[idx];
      const newVal = oldVal < 128 ? 0 : 255;
      result[idx] = newVal;
      const error = oldVal - newVal;

      if (x + 1 < w) gray[idx + 1] += error * 7 / 16;
      if (y + 1 < h) {
        if (x - 1 >= 0) gray[(y + 1) * w + (x - 1)] += error * 3 / 16;
        gray[(y + 1) * w + x] += error * 5 / 16;
        if (x + 1 < w) gray[(y + 1) * w + (x + 1)] += error * 1 / 16;
      }
    }
  }

  return result;
}
