/**
 * Web Bluetooth communication with Phomemo M110 thermal printer.
 * Based on the proven Phomymo open-source implementation.
 * 
 * Label size: 70x50mm at 203 DPI = 559x399 pixels
 * Printer width: 384 pixels (48 bytes)
 * v2 - line-by-line protocol
 */

// Phomemo BLE Service UUIDs (from Phomymo project)
const SERVICE_UUIDS = [
  0xff00,
  0xffe0,
  0xae30,
  '49535343-fe7d-4ae5-8fa9-9fafd205e455',
  '0000ff00-0000-1000-8000-00805f9b34fb',
] as const;

// Write characteristic UUIDs
const WRITE_CHAR_UUIDS = [
  0xff02,
  'bef8d6c9-9c21-4c9e-b632-bd58c1009f9f',
  '49535343-8841-43f4-a8d4-ecbe34729bb3',
];

// Printer constants
const BLE_CHUNK_SIZE = 128;
const BLE_CHUNK_DELAY_MS = 20;
const BLE_WRITE_TIMEOUT_MS = 7000;

export interface PrinterConnection {
  device: any;
  characteristic: any;
  writeMethod: 'withoutResponse' | 'withResponse';
}

/** Check if Web Bluetooth is supported */
export function isBluetoothSupported(): boolean {
  return typeof navigator !== 'undefined' && 'bluetooth' in (navigator as any);
}

/** Connect to a Phomemo M110 printer via Web Bluetooth */
export async function connectPrinter(): Promise<PrinterConnection> {
  if (!isBluetoothSupported()) {
    throw new Error('Web Bluetooth stöds inte i denna webbläsare. Använd Chrome eller Edge.');
  }

  let device: any;
  try {
    device = await (navigator as any).bluetooth.requestDevice({
      filters: [
        { namePrefix: 'M' }, { namePrefix: 'D' }, { namePrefix: 'P' },
        { namePrefix: 'Q' }, { namePrefix: 'T' }, { namePrefix: 'A' },
        { namePrefix: 'Mr.in' }, { namePrefix: 'Phomemo' },
      ],
      optionalServices: SERVICE_UUIDS as any,
    });
  } catch {
    // Fallback: show all BLE devices
    device = await (navigator as any).bluetooth.requestDevice({
      acceptAllDevices: true,
      optionalServices: SERVICE_UUIDS as any,
    });
  }

  const server = await connectWithRetry(device);

  // Find service
  let service: any = null;
  for (const uuid of SERVICE_UUIDS) {
    try {
      service = await server.getPrimaryService(uuid as any);
      break;
    } catch { /* try next */ }
  }
  if (!service) throw new Error('Kunde inte hitta skrivarens BLE-tjänst. Kontrollera att skrivaren är påslagen.');

  // Find write characteristic
  let characteristic: any = null;
  for (const uuid of WRITE_CHAR_UUIDS) {
    try {
      characteristic = await service.getCharacteristic(uuid as any);
      break;
    } catch { /* try next */ }
  }
  if (!characteristic) throw new Error('Kunde inte hitta skrivarens BLE-karaktäristik.');

  // Detect write method
  const writeMethod = characteristic.properties.writeWithoutResponse ? 'withoutResponse' : 'withResponse';

  return { device, characteristic, writeMethod };
}

/** Connect to GATT server with retry */
async function connectWithRetry(device: any, retries = 1): Promise<any> {
  for (let attempt = 0; attempt <= retries; attempt++) {
    try {
      const server = await device.gatt!.connect();
      return server;
    } catch (e) {
      if (attempt < retries) {
        await delay(300 * (attempt + 1));
      } else {
        throw new Error('Kunde inte ansluta till skrivaren. Försök stänga av och slå på den.');
      }
    }
  }
  throw new Error('Anslutning misslyckades.');
}

/** Disconnect from printer */
export function disconnectPrinter(connection: PrinterConnection): void {
  try {
    connection.device.gatt?.disconnect();
  } catch { /* ignore */ }
}

/** Send one BLE chunk with timeout so we can identify hanging steps */
async function writeChunkWithTimeout(
  conn: PrinterConnection,
  chunk: Uint8Array,
  context: string,
): Promise<void> {
  const writePromise = conn.writeMethod === 'withoutResponse'
    ? conn.characteristic.writeValueWithoutResponse(chunk)
    : conn.characteristic.writeValueWithResponse(chunk);

  await Promise.race([
    writePromise,
    delay(BLE_WRITE_TIMEOUT_MS).then(() => {
      throw new Error(`Timeout vid skrivning: ${context}`);
    }),
  ]);
}

/** Send raw bytes in chunks */
async function sendChunked(conn: PrinterConnection, data: Uint8Array, context = 'okänt steg'): Promise<void> {
  const totalChunks = Math.ceil(data.length / BLE_CHUNK_SIZE);
  for (let offset = 0; offset < data.length; offset += BLE_CHUNK_SIZE) {
    const chunk = data.slice(offset, offset + BLE_CHUNK_SIZE);
    const chunkNo = Math.floor(offset / BLE_CHUNK_SIZE) + 1;
    await writeChunkWithTimeout(conn, chunk, `${context} (${chunkNo}/${totalChunks})`);

    if (offset + BLE_CHUNK_SIZE < data.length) {
      await delay(BLE_CHUNK_DELAY_MS);
    }
  }
}

function delay(ms: number): Promise<void> {
  return new Promise(r => setTimeout(r, ms));
}

export interface PrintProgress {
  phase: string;
  percent: number;
}

/**
 * Print canvas to Phomemo M110 using Phomemo-native line-by-line protocol.
 * Based on the Phomymo open-source project's proven command sequence.
 * Canvas should already be 384px wide (generated by LabelCanvas).
 */
export async function printBitmap(
  connection: PrinterConnection,
  canvas: HTMLCanvasElement,
  copies: number = 1,
  density: number = 8,
  onProgress?: (p: PrintProgress) => void,
): Promise<void> {
  onProgress?.({ phase: 'Förbereder bild...', percent: 5 });

  const width = canvas.width;
  const height = canvas.height;
  const ctx = canvas.getContext('2d')!;
  const imageData = ctx.getImageData(0, 0, width, height);

  // Dither to 1-bit monochrome
  onProgress?.({ phase: 'Dithar bild...', percent: 10 });
  const pixels = ditherToMonochrome(imageData);

  // Convert to bitmap: 1 bit per pixel, MSB first, 1 = black dot
  const bytesPerRow = Math.ceil(width / 8);
  const bitmapRows: Uint8Array[] = [];
  for (let y = 0; y < height; y++) {
    const row = new Uint8Array(bytesPerRow);
    for (let x = 0; x < width; x++) {
      if (pixels[y * width + x] === 0) { // black pixel
        const byteIdx = Math.floor(x / 8);
        const bitIdx = 7 - (x % 8);
        row[byteIdx] |= (1 << bitIdx);
      }
    }
    bitmapRows.push(row);
  }

  const clampedDensity = Math.max(1, Math.min(15, density));

  for (let copy = 0; copy < copies; copy++) {
    const copyLabel = copies > 1 ? ` (${copy + 1}/${copies})` : '';
    const basePercent = 15 + (copy / copies) * 80;

    // 1. Initialize printer
    onProgress?.({ phase: `Initierar skrivare${copyLabel}...`, percent: basePercent });
    await sendChunked(connection, new Uint8Array([0x1B, 0x40]), 'print:init');
    await delay(100);

    // 2. Set concentration/density: 0x1F 0x11 0x37 [density]
    await sendChunked(connection, new Uint8Array([0x1F, 0x11, 0x37, clampedDensity]), 'print:densitet');
    await delay(20);

    // 3. Set paper type: gap label detection (0x1F 0x11 0x02 0x04)
    await sendChunked(connection, new Uint8Array([0x1F, 0x11, 0x02, 0x04]), 'print:mediatyp');
    await delay(20);

    // 4. Start print job: 0x10 0xFF 0xFE 0x01
    await sendChunked(connection, new Uint8Array([0x10, 0xFF, 0xFE, 0x01]), 'print:start-jobb');
    await delay(50);

    // 5. Send bitmap line by line with 0x00 prefix per line
    onProgress?.({ phase: `Skickar bilddata${copyLabel}...`, percent: basePercent + 10 });
    
    // Build all line data: each line = 0x00 + bytesPerRow bytes of bitmap
    const lineSize = 1 + bytesPerRow; // prefix byte + data
    const allData = new Uint8Array(height * lineSize);
    for (let y = 0; y < height; y++) {
      const offset = y * lineSize;
      allData[offset] = 0x00; // line prefix
      allData.set(bitmapRows[y], offset + 1);
    }

    // Send in BLE chunks with progress
    const totalChunks = Math.ceil(allData.length / BLE_CHUNK_SIZE);
    for (let i = 0; i < totalChunks; i++) {
      const chunk = allData.slice(i * BLE_CHUNK_SIZE, (i + 1) * BLE_CHUNK_SIZE);
      await writeChunkWithTimeout(connection, chunk, `bilddata (${i + 1}/${totalChunks})`);
      if (i < totalChunks - 1) await delay(BLE_CHUNK_DELAY_MS);

      if (i % 10 === 0) {
        const chunkPercent = basePercent + 10 + (i / totalChunks) * 60 * (1 / copies);
        onProgress?.({ phase: `Skickar bilddata${copyLabel}...`, percent: Math.min(95, chunkPercent) });
      }
    }

    // 6. End print job / form feed: 0x1A
    await delay(100);
    await sendChunked(connection, new Uint8Array([0x1A]), 'print:avsluta');
    await delay(500);

    if (copy < copies - 1) await delay(500);
  }

  onProgress?.({ phase: 'Klar!', percent: 100 });
}

export interface PrinterDiagnosticResult {
  ok: boolean;
  failedStep?: string;
  errorMessage?: string;
  logs: string[];
  durationMs: number;
}

/**
 * Runs a compact BLE diagnostic print to identify where printer communication hangs.
 */
export async function runPrinterDiagnostic(
  connection: PrinterConnection,
  onProgress?: (p: PrintProgress) => void,
): Promise<PrinterDiagnosticResult> {
  const startedAt = performance.now();
  const logs: string[] = [];
  let currentStep = '';

  const runStep = async (label: string, percent: number, command: Uint8Array, waitMs = 20) => {
    currentStep = label;
    logs.push(`▶ ${label}`);
    onProgress?.({ phase: `Diagnostik: ${label}`, percent });
    await sendChunked(connection, command, `diagnostik:${label}`);
    if (waitMs > 0) await delay(waitMs);
    logs.push(`✅ ${label}`);
  };

  try {
    await runStep('Init', 10, new Uint8Array([0x1B, 0x40]), 80);
    await runStep('Densitet', 25, new Uint8Array([0x1F, 0x11, 0x37, 0x08]));
    await runStep('Mediatyp (gap)', 40, new Uint8Array([0x1F, 0x11, 0x02, 0x04]));
    await runStep('Starta jobb', 55, new Uint8Array([0x10, 0xFF, 0xFE, 0x01]), 40);

    currentStep = 'Skicka testmönster';
    logs.push(`▶ ${currentStep}`);
    onProgress?.({ phase: 'Diagnostik: Skickar testmönster', percent: 75 });

    const bytesPerRow = 48;
    const testRows = 32;
    const lineSize = 1 + bytesPerRow;
    const testData = new Uint8Array(testRows * lineSize);

    for (let y = 0; y < testRows; y++) {
      const offset = y * lineSize;
      testData[offset] = 0x00;
      const fillByte = y % 2 === 0 ? 0xff : 0x00;
      for (let x = 0; x < bytesPerRow; x++) {
        testData[offset + 1 + x] = fillByte;
      }
    }

    await sendChunked(connection, testData, 'diagnostik:testmönster');
    await delay(60);
    logs.push(`✅ ${currentStep}`);

    await runStep('Avsluta jobb', 92, new Uint8Array([0x1A]), 300);
    onProgress?.({ phase: 'Diagnostik klar', percent: 100 });

    return {
      ok: true,
      logs,
      durationMs: Math.round(performance.now() - startedAt),
    };
  } catch (error: any) {
    const errorMessage = error?.message || 'Okänt fel';
    logs.push(`❌ ${currentStep}: ${errorMessage}`);

    return {
      ok: false,
      failedStep: currentStep || 'okänt steg',
      errorMessage,
      logs,
      durationMs: Math.round(performance.now() - startedAt),
    };
  }
}

/**
 * Floyd-Steinberg dithering: converts RGBA image data to array of 0 (black) or 255 (white).
 */
function ditherToMonochrome(imageData: ImageData): Uint8Array {
  const w = imageData.width;
  const h = imageData.height;
  const data = imageData.data;

  const gray = new Float32Array(w * h);
  for (let i = 0; i < w * h; i++) {
    const r = data[i * 4];
    const g = data[i * 4 + 1];
    const b = data[i * 4 + 2];
    const a = data[i * 4 + 3];
    const alpha = a / 255;
    gray[i] = (0.299 * r + 0.587 * g + 0.114 * b) * alpha + 255 * (1 - alpha);
  }

  const result = new Uint8Array(w * h);
  for (let y = 0; y < h; y++) {
    for (let x = 0; x < w; x++) {
      const idx = y * w + x;
      const oldVal = gray[idx];
      const newVal = oldVal < 128 ? 0 : 255;
      result[idx] = newVal;
      const error = oldVal - newVal;

      if (x + 1 < w) gray[idx + 1] += error * 7 / 16;
      if (y + 1 < h) {
        if (x - 1 >= 0) gray[(y + 1) * w + (x - 1)] += error * 3 / 16;
        gray[(y + 1) * w + x] += error * 5 / 16;
        if (x + 1 < w) gray[(y + 1) * w + (x + 1)] += error * 1 / 16;
      }
    }
  }

  return result;
}
