project_id = "plwchuzidrjgyuepwdcl"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.brewfather-batches]
verify_jwt = false

[functions.brewfather-readings]
verify_jwt = false

[functions.sync-brew-data]
verify_jwt = false

[functions.full-sync-brew-data]
verify_jwt = false

[functions.rapt-auth]
verify_jwt = false

[functions.rapt-pills]
verify_jwt = false

[functions.rapt-temp-controllers]
verify_jwt = false

[functions.sync-rapt-data]
verify_jwt = false
