// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@3.0.4";

// src/lib/mcp/tools/list-controllers.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@3.0.4";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.110.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv(["SUPABASE_PUBLISHABLE_KEY", "VITE_SUPABASE_PUBLISHABLE_KEY"]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-controllers.ts
var list_controllers_default = defineTool({
  name: "list_controllers",
  title: "List tank controllers",
  description: "List all fermentation tank controllers and the glycol cooler with current and target temperature.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_args, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await supabaseForUser(ctx).from("rapt_temp_controllers").select("id, name, actual_temp, target_temp, is_glycol_cooler, cooling_enabled, heating_enabled, last_update").order("name");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const controllers = (data ?? []).map((c) => ({
      id: c.id,
      name: c.name,
      actual_temp: c.actual_temp,
      target_temp: c.target_temp,
      is_glycol_cooler: c.is_glycol_cooler,
      cooling_enabled: c.cooling_enabled,
      heating_enabled: c.heating_enabled,
      last_update: c.last_update
    }));
    return { content: [{ type: "text", text: JSON.stringify(controllers) }], structuredContent: { controllers } };
  }
});

// src/lib/mcp/tools/get-live-state.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@3.0.4";
var get_live_state_default = defineTool2({
  name: "get_live_state",
  title: "Get Pi live state",
  description: "Read the Raspberry Pi's latest live regulation state per controller (mode, relays, duty, heartbeat).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_args, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await supabaseForUser(ctx).from("pi_live_state").select("controller_id, actual_temp, target_temp, mode, cooling_relay_on, heating_relay_on, duty_pct, glycol_temp, last_heartbeat");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const states = (data ?? []).map((s) => ({
      controller_id: s.controller_id,
      actual_temp: s.actual_temp,
      target_temp: s.target_temp,
      mode: s.mode,
      cooling_relay_on: s.cooling_relay_on,
      heating_relay_on: s.heating_relay_on,
      duty_pct: s.duty_pct,
      glycol_temp: s.glycol_temp,
      last_heartbeat: s.last_heartbeat
    }));
    return { content: [{ type: "text", text: JSON.stringify(states) }], structuredContent: { states } };
  }
});

// src/lib/mcp/tools/get-brew-status.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@3.0.4";
import { z } from "npm:zod@^3.25.76";
var get_brew_status_default = defineTool3({
  name: "get_brew_status",
  title: "Get brew status",
  description: "Read a brew's fermentation status from the Pi: measured OG and its source, fermentation start and its source, pitch details, expected FG. When og_source is 'pill' the OG was measured by the pill; when fermentation_start_source is 'pitch' the start time is when the brewer pitched the yeast \u2014 do not ask about it.",
  inputSchema: { source_id: z.string().describe("The brew's source_id") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (args, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const client = supabaseForUser(ctx);
    const { data: status, error } = await client.from("brew_status").select("source_id, pi_brew_id, phase, og, og_source, og_measured, fg_expected, fermentation_start, fermentation_start_source, pitch, sg_current, attenuation_pct, updated_at").eq("source_id", args.source_id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!status) return { content: [{ type: "text", text: "No status for that source_id" }], isError: true };
    const brewIds = [status.source_id, status.pi_brew_id].filter(Boolean);
    const { data: brew } = await client.from("brew_readings").select("id, name, original_gravity, recipe").in("id", brewIds).limit(1).maybeSingle();
    const result = {
      source_id: status.source_id,
      name: brew?.name ?? null,
      phase: status.phase,
      og: status.og,
      og_source: status.og_source,
      og_planned: brew?.recipe?.og ?? null,
      fg_expected: status.fg_expected,
      fermentation_start: status.fermentation_start,
      fermentation_start_source: status.fermentation_start_source,
      pitch: status.pitch,
      sg_current: status.sg_current,
      attenuation_pct: status.attenuation_pct,
      updated_at: status.updated_at
    };
    return { content: [{ type: "text", text: JSON.stringify(result) }], structuredContent: result };
  }
});

// src/lib/mcp/index.ts
var projectRef = "plwchuzidrjgyuepwdcl";
var mcp_default = defineMcp({
  name: "brew-monitor-tv",
  title: "brew-monitor-tv",
  version: "0.1.0",
  instructions: "Read-only access to the Brew Monitor dashboard. The Raspberry Pi controls all regulation; these tools only read tank temperatures and the Pi's live state.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_controllers_default, get_live_state_default, get_brew_status_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@3.0.4/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
